<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
                <!-- BLOCO -->
                <!-- dashboard1PageContainerHeaderDesktop -->
                <!-- HEADER DESKTOP-->

                <?php
                    router::identify('dashboard1PageContainerHeaderDesktopBlock', $params);
                ?>

                <!-- END HEADER DESKTOP-->
                <!-- BLOCO -->

                <section class="au-breadcrumb m-t-75">
                    <div class="section__content section__content--p30">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">

                                    <!-- BLOCO -->

                                    <!-- BLOCO -->
                                    <!-- dashboard1PageContainerBreakcrumb -->
                                    <!-- BREADCRUMB-->

                                    <?php
                                        router::identify('dashboard1PageContainerBreakcrumbBlock', $params);
                                    ?>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <!-- END BREADCRUMB-->

                <!-- BLOCO -->
                <!-- dashboard1PageContainerAlertsBlock -->

                    <?php
                        router::identify('dashboard1PageContainerAlertsBlock', $params);
                    ?>

                <!-- BLOCO -->

                <!-- BLOCO -->

                <section class="statistic">
                    <div class="section__content section__content--p30">
                        <div class="container-fluid">
                            <div class="row">

                                <!-- BLOCO -->
                                <!-- dashboard1PageContainerPerfilBlock -->
                                <!-- STATISTIC-->

                                <?php
                                    router::page($params);
                                ?>

                            </div>
                        </div>
                    </div>
                </section>

                <!-- END STATISTIC-->
                <!-- BLOCO -->

                <!-- <section class="statistic">
                    <div class="section__content section__content--p30">
                        <div class="container-fluid">
                            <div class="row"> -->

                                <!-- BLOCO -->
                                <!-- dashboard1PageContainerStatistic -->
                                <!-- STATISTIC-->

                                <!-- <?php
                                    router::identify('dashboard1PageContainerStatisticBlock', $params);
                                ?> -->

                            <!-- </div>
                        </div>
                    </div>
                </section> -->

                <!-- END STATISTIC-->
                <!-- BLOCO -->

                <!-- <section>
                    <div class="section__content section__content--p30">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-xl-8"> -->

                                    <!-- BLOCO -->
                                    <!-- dashboard1PageContainerRecentReport2Block -->                                    
                                    <!-- RECENT REPORT 2-->

                                    <!-- <?php
                                        router::identify('dashboard1PageContainerRecentReport2Block', $params);
                                    ?> -->
                                    
                                    <!-- END RECENT REPORT 2 -->

                                <!-- </div>
                                <div class="col-xl-4"> -->

                                    <!-- BLOCO -->
                                    <!-- dashboard1PageContainerTaskProgressBlock -->
                                    <!-- TASK PROGRESS-->

                                    <!-- <?php
                                        router::identify('dashboard1PageContainerTaskProgressBlock', $params);
                                    ?> -->

                                    <!-- END TASK PROGRESS-->

                                <!-- </div>
                            </div>
                        </div>
                    </div>
                </section> -->

                <!-- MAIN CONTENT 1 -->

                <!-- <section>
                    <div class="section__content section__content--p30">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-xl-6"> -->

                                    <!-- BLOCO -->
                                    <!-- dashboard1PageContainerUserDataBlock -->
                                    <!-- USER DATA-->

                                    <!-- <?php
                                        router::identify('dashboard1PageContainerUserDataBlock', $params);
                                    ?> -->
                                    
                                    <!-- END USER DATA-->

                                <!-- </div>
                                <div class="col-xl-6"> -->

                                    <!-- BLOCO -->
                                    <!-- dashboard1PageContainerMapDataBlock -->
                                    <!-- MAP DATA-->

                                    <!-- <?php
                                        router::identify('dashboard1PageContainerMapDataBlock', $params);
                                    ?> -->
                                    
                                    <!-- END MAP DATA-->

                                <!-- </div>
                            </div>
                        </div>
                    </div>
                </section> -->

                <!-- MAIN CONTENT 2 -->

                    <section>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">

                                    <!-- BLOCO -->
                                    <!-- dashboard1PageContainerCopyrightBlock -->
                                    <!-- COPYRIGHT -->

                                    <?php
                                        router::identify('dashboard1PageContainerCopyrightBlock', $params);
                                    ?>

                                    <!-- BLOCO -->
                                    <!-- END COPYRIGHT -->
                                
                                </div>
                            </div>
                        </div>
                    </section>