<?php
    use douggonsouza\routes\router;

    $existAlerts = router::alerts()::exist();
?>
                <section class="statistic">
                    <div class="section__content section__content--p30">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card-body">
                                        <?php
                                            if($existAlerts){
                                                echo router::alerts()::get();
                                            }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div> 
                    </div>
                </section>