<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
    use douggonsouza\logged\logged;
    use douggonsouza\logged\models\user;
    use douggonsouza\discovery\models\accessPage;
    use douggonsouza\propertys\propertys;

    $perfil = (new user())->perfil(logged::getId());
    if(isset($perfil)){
        $aPages = (new accessPage())->pages($perfil->access_id);
    }
?>
        <!-- HEADER MOBILE -->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="index.html">
                            <img src="<?= router::assets("/images/icon/logo-douggs.png", assets::ABSOLUTE_URL) ?>" alt="CoolAdmin" />
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner">

                                    <div>
                                        <ul class="nav flex-column flex-nowrap">
                                            <?php
                                                $count = 0;
                                                $stepOne = '';
                                                foreach($aPages as $page){
                                                    if($page['stepOneShowName'] != $stepOne){
                                                        echo('
                                                        <li class="nav-item has-sub">
                                                            <a class="nav-link collapsed text-truncate" href="#msubmenu' . $count . '" data-toggle="collapse" data-target="#msubmenu' . $count . '"><i class="' . $page['icon'] . '"></i> <span class="d-none d-sm-inline">' . router::label($page['stepOneShowName']) . '</span></a>
                                                            <div class="collapse" id="msubmenu' . $count . '" aria-expanded="false">
                                                                <ul class="flex-column pl-2">');
                                                    }
                                                
                                                                    echo('
                                                                    <li class="nav-item">
                                                                        <a class="nav-link p-1 text-truncate" href="'. router::getUsages()->getHost(). $page['url'] . '">' . router::label($page['showName']) . '</a>
                                                                    </li>
                                                                    ');
                                                    
                                                    $stepOne = $page['stepOneShowName'];
                                                    if($page['stepOneShowName'] != $stepOne){
                                                        echo('
                                                                <\ul>
                                                            <\div>
                                                        </li>
                                                    ');
                                                    }
                                                    $count++;
                                                }
                                            ?>
                                        </ul>
                                    </div>

                                </span>
                            </span>
                        </button>

                        
                    </div>
                </div>
            </div>

            <!-- <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">
                        <li class="has-sub">
                            <a class="js-arrow" href="#">
                                <i class="fas fa-tachometer-alt"></i><?= router::label('dashboard'); ?>
                                <span class="arrow">
                                    <i class="fas fa-angle-down"></i>
                                </span>
                            </a>
                            <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                                <li>
                                    <a href="index.html">Dashboard 1</a>
                                </li>
                                <li>
                                    <a href="index2.html">Dashboard 2</a>
                                </li>
                                <li>
                                    <a href="index3.html">Dashboard 3</a>
                                </li>
                                <li>
                                    <a href="index4.html">Dashboard 4</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="chart.html">
                                <i class="fas fa-chart-bar"></i>Charts</a>
                        </li>
                        <li>
                            <a href="table.html">
                                <i class="fas fa-table"></i>Tables</a>
                        </li>
                        <li>
                            <a href="form.html">
                                <i class="far fa-check-square"></i>Forms</a>
                        </li>
                        <li>
                            <a href="calendar.html">
                                <i class="fas fa-calendar-alt"></i>Calendar</a>
                        </li>
                        <li>
                            <a href="map.html">
                                <i class="fas fa-map-marker-alt"></i>Maps</a>
                        </li>
                        <li class="has-sub">
                            <a class="js-arrow" href="#">
                                <i class="fas fa-copy"></i>Pages</a>
                            <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                                <li>
                                    <a href="login.html">Login</a>
                                </li>
                                <li>
                                    <a href="register.html">Register</a>
                                </li>
                                <li>
                                    <a href="forget-pass.html">Forget Password</a>
                                </li>
                            </ul>
                        </li>
                        <li class="has-sub">
                            <a class="js-arrow" href="#">
                                <i class="fas fa-desktop"></i>UI Elements</a>
                            <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                                <li>
                                    <a href="button.html">Button</a>
                                </li>
                                <li>
                                    <a href="badge.html">Badges</a>
                                </li>
                                <li>
                                    <a href="tab.html">Tabs</a>
                                </li>
                                <li>
                                    <a href="card.html">Cards</a>
                                </li>
                                <li>
                                    <a href="alert.html">Alerts</a>
                                </li>
                                <li>
                                    <a href="progress-bar.html">Progress Bars</a>
                                </li>
                                <li>
                                    <a href="modal.html">Modals</a>
                                </li>
                                <li>
                                    <a href="switch.html">Switchs</a>
                                </li>
                                <li>
                                    <a href="grid.html">Grids</a>
                                </li>
                                <li>
                                    <a href="fontawesome.html">Fontawesome Icon</a>
                                </li>
                                <li>
                                    <a href="typo.html">Typography</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav> -->
        </header>