<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
                                    <div class="au-breadcrumb-content">
                                        <div class="au-breadcrumb-left">
                                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                                <li class="list-inline-item active">
                                                    <a href="#">Home</a>
                                                </li>
                                                <li class="list-inline-item seprate">
                                                    <span>/</span>
                                                </li>
                                                <li class="list-inline-item">
                                                    <a href="#">Dashboard</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>