<?php
    use douggonsouza\routes\router;
    use \douggonsouza\alerts\alerts;
    use douggonsouza\benchmarck\assets\assets;

    $existAlerts = router::alerts()::exist();
?>
                    <div class="section__content section__content--p30">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card-body">
                                        <div class="sufee-alert alert with-close alert-primary alert-dismissible fade show">
											<span class="badge badge-pill badge-primary">Success</span>
											You successfully read this important alert.
											<button type="button" class="close" data-dismiss="alert" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
                                        <?php
                                            if($existAlerts){
                                                echo router::alerts()::get();
                                            }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div> 
                    </div>