<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
                <!-- BLOCO -->

                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">

                                    <!-- BLOCO -->
                                    <!-- dashboard1PageContainerBreakcrumb -->
                                    <!-- BREADCRUMB-->

                                    <?php
                                        router::identifyBlock('dashboardPageContainerBreakcrumbBlock', $params);
                                    ?>
                                    
                                    <!-- BLOCO -->
                            </div>
                        </div>
                    </div>
                </div>

                <!-- END BREADCRUMB-->

                <div class="section__content section__content--p30">
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body card-block">
                                        <div class="col-md-12">
                                            <div class="overview-wrap">
                                                <button class="au-btn au-btn-icon au-btn--blue">
                                                    <?= router::label('add'); ?>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body card-block">
                                        <div class="col-md-12">
                                            <div class="overview-wrap">
                                                <h2 class="title-1"><?= router::label('step_one'); ?></h2>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body card-block">
                                        <form action="" method="post">
                                            <div class="form-group">
                                                <label for="showName" class=" form-control-label"><?= router::label('showName'); ?></label>
                                                <input type="text" id="showName" name="showName" placeholder="<?= router::label('showName'); ?>" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="description" class=" form-control-label"><?= router::label('description'); ?></label>
                                                <textarea type="text" id="description" name="description" rows="9" placeholder="<?= router::label('description'); ?>" class="form-control"></textarea>
                                            </div>
                                            <div class="form-group">
                                                <label for="icon" class=" form-control-label"><?= router::label('icon'); ?></label>
                                                <input type="text" id="icon" name="icon" placeholder="<?= router::label('icon'); ?>" class="form-control">
                                            </div>
                                            <div class="card-footer">
                                                <input type="hidden" name="pub_key" value="UHJpbWVpcm8gTsOtdmVs">
                                                <button type="submit" class="btn btn-primary btn-sm">
                                                    <i class="fa fa-dot-circle-o"></i> <?= router::label('submit'); ?>
                                                </button>
                                                <button type="reset" class="btn btn-danger btn-sm">
                                                    <i class="fa fa-ban"></i> <?= router::label('reset'); ?>
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>