<?php 
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
                <section class="au-breadcrumb2">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">

                                <!-- BLOCO -->
                                <!-- dashboard2PageContentBreadcrumbBlock-->
                                <!-- BREADCRUMB-->

                                <?php
                                    router::identify('dashboard2PageContentBreadcrumbBlock', $params)
                                ?>

                            </div>
                        </div>
                    </div>
                </section>
                <!-- END BREADCRUMB-->

                <section class="welcome p-t-10">
                    <div class="container">
                        <div class="row">

                            <!-- BLOCO -->
                            <!-- dashboard2PageContentWelcomeBlock-->
                            <!-- WELCOME-->

                            <?php
                                router::identify('dashboard2PageContentWelcomeBlock', $params);
                            ?>

                        </div>
                    </div>
                </section>
                <!-- END WELCOME-->

                <section class="statistic statistic2">
                    <div class="container">
                        <div class="row">

                            <!-- BLOCO -->
                            <!-- dashboard2PageContentStatisticBlock-->
                            <!-- STATISTIC-->

                            <?php
                                router::identify('dashboard2PageContentStatisticBlock', $params)
                            ?>

                        </div>
                    </div>
                </section>
                <!-- END STATISTIC-->

                <!-- BLOCO -->
                <!-- dashboard2PageContentStatisticChartBlock-->
                <!-- STATISTIC CHART-->

                <?php
                    router::identify('dashboard2PageContentStatisticChartBlock', $params)
                ?>

                <!-- END STATISTIC CHART-->

                <!-- BLOCO -->
                <!-- dashboard2PageContentDataTableBlock-->
                <!-- DATA TABLE-->

                <?php
                    router::identify('dashboard2PageContentDataTableBlock', $params)
                ?>

                <!-- END DATA TABLE-->

                <section class="p-t-60 p-b-20">
                    <div class="container">
                        <div class="row">

                            <!-- BLOCO -->
                            <!-- dashboard2PageContentCopyrightBlock-->
                            <!-- COPYRIGHT-->

                            <?php
                                router::identify('dashboard2PageContentCopyrightBlock', $params)
                            ?>
                            
                        </div>
                    </div>
                </section>
                <!-- END COPYRIGHT-->