<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
            <!-- HEADER DESKTOP-->

            <?php
                router::identify('dashboardPageContainerHeaderDesktopBlock', $params)
            ?>

            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->

            <?php
                router::identify('dashboardPageContainerMainContentBlock', $params)
            ?>

            <!-- END MAIN CONTENT-->