<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
                <header class="header-desktop2">
                    <div class="section__content section__content--p30">
                        <div class="container-fluid">
                            <div class="header-wrap2">

                                <!-- BLOCO -->
                                <!-- dashboard1PageContainerHeaderWrapBlock -->
                                <!-- HEADER WRAP -->

                                <?php
                                    router::block('dashboard1PageContainerHeaderWrapBlock', $params);
                                ?>

                                <!-- BLOCO -->

                            </div>
                        </div>
                    </div>
                </header>

                <!-- BLOCO -->

                <aside class="menu-sidebar2 js-right-sidebar d-block d-lg-none">

                    <!-- BLOCO -->
                    <!-- dashboard1PageContainerMenuSidebarBlock -->
                    <!-- MENU SIDEBAR 2 -->

                    <?php
                        router::block('dashboard1PageContainerMenuSidebarBlock', $params);
                    ?>

                    <!-- BLOCO -->

                </aside>