<?php
    use douggonsouza\routes\router;
?>
            <!-- HEADER DESKTOP-->

            <?php
                router::block('dashboardPageContainerHeaderDesktopBlock', $params)
            ?>

            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->

            <!-- dashboardPageContainerMainContentBlock -->

            <?php
                router::block('dashboardPageContainerMainContentBlock', $params)
            ?>

            <!-- END MAIN CONTENT-->