<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
                                    <div class="task-progress">
                                        <h3 class="title-3">task progress</h3>
                                        <div class="au-skill-container">
                                            <div class="au-progress">
                                                <span class="au-progress__title">Web Design</span>
                                                <div class="au-progress__bar">
                                                    <div class="au-progress__inner js-progressbar-simple" role="progressbar" data-transitiongoal="90">
                                                        <span class="au-progress__value js-value"></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="au-progress">
                                                <span class="au-progress__title">HTML5/CSS3</span>
                                                <div class="au-progress__bar">
                                                    <div class="au-progress__inner js-progressbar-simple" role="progressbar" data-transitiongoal="85">
                                                        <span class="au-progress__value js-value"></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="au-progress">
                                                <span class="au-progress__title">WordPress</span>
                                                <div class="au-progress__bar">
                                                    <div class="au-progress__inner js-progressbar-simple" role="progressbar" data-transitiongoal="95">
                                                        <span class="au-progress__value js-value"></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="au-progress">
                                                <span class="au-progress__title">Support</span>
                                                <div class="au-progress__bar">
                                                    <div class="au-progress__inner js-progressbar-simple" role="progressbar" data-transitiongoal="95">
                                                        <span class="au-progress__value js-value"></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>