<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
                                    <div class="map-data m-b-40">
                                        <h3 class="title-3 m-b-30">
                                            <i class="zmdi zmdi-map"></i>map data</h3>
                                        <div class="filters">
                                            <div class="rs-select2--dark rs-select2--md m-r-10 rs-select2--border">
                                                <select class="js-select2" name="property">
                                                    <option selected="selected">All Worldwide</option>
                                                    <option value="">Products</option>
                                                    <option value="">Services</option>
                                                </select>
                                                <div class="dropDownSelect2"></div>
                                            </div>
                                            <div class="rs-select2--dark rs-select2--sm rs-select2--border">
                                                <select class="js-select2 au-select-dark" name="time">
                                                    <option selected="selected">All Time</option>
                                                    <option value="">By Month</option>
                                                    <option value="">By Day</option>
                                                </select>
                                                <div class="dropDownSelect2"></div>
                                            </div>
                                        </div>
                                        <div class="map-wrap m-t-45 m-b-80">
                                            <div id="vmap" style="height: 284px;"></div>
                                        </div>
                                        <div class="table-wrap">
                                            <div class="table-responsive table-style1">
                                                <table class="table">
                                                    <tbody>
                                                        <tr>
                                                            <td>United States</td>
                                                            <td>$119,366.96</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Australia</td>
                                                            <td>$70,261.65</td>
                                                        </tr>
                                                        <tr>
                                                            <td>United Kingdom</td>
                                                            <td>$46,399.22</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                            <div class="table-responsive table-style1">
                                                <table class="table">
                                                    <tbody>
                                                        <tr>
                                                            <td>Germany</td>
                                                            <td>$20,366.96</td>
                                                        </tr>
                                                        <tr>
                                                            <td>France</td>
                                                            <td>$10,366.96</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Russian</td>
                                                            <td>$5,366.96</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>