<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
                <!-- BLOCO -->
                <!-- dashboard1PageContainerHeaderDesktop -->
                <!-- HEADER DESKTOP-->

                <?php
                    router::identify('dashboard1PageContainerHeaderDesktopBlock', $params);
                ?>

                <!-- END HEADER DESKTOP-->

                <section>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">

                                <!-- BLOCO -->
                                <!-- dashboard1PageContainerAlertsBlock -->

                                    <?php
                                        router::identify('dashboard1PageContainerAlertsBlock', $params);
                                    ?>

                                <!-- BLOCO -->

                            </div>
                        </div>
                    </div>
                </section>

                <!-- BLOCO -->

                <!-- BLOCO -->
                <!-- dashboard1PageContainerPageBlock -->
                <!-- STATISTIC-->

                <?php
                    router::identify('dashboard1PageContainerPageBlock', $params);
                ?>

                <!-- MAIN CONTENT 2 -->

                <section>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">

                                <!-- BLOCO -->
                                <!-- dashboard1PageContainerCopyrightBlock -->
                                <!-- COPYRIGHT -->

                                <?php
                                    router::identify('dashboard1PageContainerCopyrightBlock', $params);
                                ?>

                                <!-- BLOCO -->
                                <!-- END COPYRIGHT -->
                                
                            </div>
                        </div>
                    </div>
                </section>