<?php
    use douggonsouza\routes\router;

    $existAlerts = router::alerts()::exist();
?>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card-body">
                                <?php
                                    if($existAlerts){
                                        echo router::alerts()::get();
                                    }
                                ?>
                            </div>
                        </div>
                    </div>