<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>

        <!-- BLOCO -->
            <div class="page-content--bge5">
                <div class="container">

                <!-- BLOCO -->
                <!-- forgetpassPageContentAlertsBlock -->

                    <?php
                        router::block('forgetpassPageContentAlertsBlock', $params);
                    ?>

                <!-- BLOCO -->
                    
                    <div class="login-wrap">
                        <div class="login-content">
                            <div class="login-logo">
                                <a href="#">
                                    <img src="<?= router::assets("/images/icon/logo-douggs.png", assets::ABSOLUTE_URL) ?>" alt="CoolAdmin">
                                </a>
                            </div>
                            <div class="login-form">
                                <form action="" method="post">
                                    <div class="form-group">
                                        <label>Email Address</label>
                                        <input class="au-input au-input--full" type="email" name="email" placeholder="Email">
                                    </div>
                                    <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">submit</button>
                                </form>
                            </div>
                        </div>


                    </div>
                </div>
            </div>