<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
        <!-- Fontfaces CSS-->
        <link href="<?= router::assets("/css/font-face.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/font-awesome-4.7/css/font-awesome.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/font-awesome-5/css/fontawesome-all.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/mdi-font/css/material-design-iconic-font.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <!-- Bootstrap CSS-->
        <link href="<?= router::assets("/vendor/bootstrap-4.1/bootstrap.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <!-- Vendor CSS-->
        <link href="<?= router::assets("/vendor/animsition/animsition.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/wow/animate.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/css-hamburgers/hamburgers.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/slick/slick.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/select2/select2.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <link href="<?= router::assets("/vendor/perfect-scrollbar/perfect-scrollbar.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">
        <!-- Main CSS-->
        <link href="<?= router::assets("/css/theme.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet" media="all">