<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
            <div class="page-content--bge5">
                <div class="container">
                    <div class="login-wrap">
                        <div class="login-content">
                            <div class="login-logo">
                                <a href="#">
                                    <img src="<?= router::assets("/images/icon/logo-douggs.png", assets::ABSOLUTE_URL) ?>" alt="CoolAdmin">
                                </a>
                            </div>
                            <div class="login-form">
                                <form action="" method="post">
                                    <div class="form-group">
                                        <label><?= router::label('email'); ?></label>
                                        <input class="au-input au-input--full" type="email" name="email" placeholder="<?= router::label('email'); ?>">
                                    </div>
                                    <div class="form-group">
                                        <label><?= router::label('password'); ?></label>
                                        <input class="au-input au-input--full" type="password" name="password" placeholder="<?= router::label('password'); ?>">
                                    </div>
                                    <div class="login-checkbox">
                                        <label>
                                            <input type="checkbox" name="remember"><?= router::label('remember'); ?>
                                        </label>
                                        <label>
                                            <a href="#"><?= router::label('forgotten'); ?></a>
                                        </label>
                                    </div>
                                    <input type="hidden" name="pub_key" value="bG9naW5fZm9ybQ==">
                                    <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit"><?= router::label('sign_in'); ?></button>
                                    <!-- <div class="social-login-content">
                                        <div class="social-button">
                                            <button class="au-btn au-btn--block au-btn--blue m-b-20"><?= router::label('register_with_facebook'); ?></button>
                                            <button class="au-btn au-btn--block au-btn--blue2"><?= router::label('register_with_twitter'); ?></button>
                                        </div>
                                    </div> -->
                                </form>
                                <div class="register-link">
                                    <p>
                                    <?= router::label('not_have_account'); ?>
                                        <a href="#"><?= router::label('sign_up'); ?></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>