<?php 
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
        <!-- Jquery JS-->
        <script src="<?= router::assets("/vendor/jquery-3.2.1.min.js", assets::ABSOLUTE_URL) ?>"></script>
        <!-- Bootstrap JS-->
        <script src="<?= router::assets("/vendor/bootstrap-4.1/popper.min.js", assets::ABSOLUTE_URL) ?>"></script>
        <script src="<?= router::assets("/vendor/bootstrap-4.1/bootstrap.min.js", assets::ABSOLUTE_URL) ?>"></script>
        <!-- Vendor JS       -->
        <script src="<?= router::assets("/vendor/slick/slick.min.js", assets::ABSOLUTE_URL) ?>">
        </script>
        <script src="<?= router::assets("/vendor/wow/wow.min.js", assets::ABSOLUTE_URL) ?>"></script>
        <script src="<?= router::assets("/vendor/animsition/animsition.min.js", assets::ABSOLUTE_URL) ?>"></script>
        <script src="<?= router::assets("/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js", assets::ABSOLUTE_URL) ?>">
        </script>
        <script src="<?= router::assets("/vendor/counter-up/jquery.waypoints.min.js", assets::ABSOLUTE_URL) ?>"></script>
        <script src="<?= router::assets("/vendor/counter-up/jquery.counterup.min.js", assets::ABSOLUTE_URL) ?>">
        </script>
        <script src="<?= router::assets("/vendor/circle-progress/circle-progress.min.js", assets::ABSOLUTE_URL) ?>"></script>
        <script src="<?= router::assets("/vendor/perfect-scrollbar/perfect-scrollbar.js", assets::ABSOLUTE_URL) ?>"></script>
        <script src="<?= router::assets("/vendor/chartjs/Chart.bundle.min.js", assets::ABSOLUTE_URL) ?>"></script>
        <script src="<?= router::assets("/vendor/select2/select2.min.js", assets::ABSOLUTE_URL) ?>">
        </script>
        <!-- Main JS-->
        <script src="<?= router::assets("/js/main.js", assets::ABSOLUTE_URL) ?>"></script>
        <!-- Bootstrap Date-Picker Plugin -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
