<?php 
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
            <div class="page-content--bge5">
                <div class="container">
                    <div class="login-wrap">
                        <div class="login-content">
                            <div class="login-logo">
                                <a href="#">
                                    <img src="<?= router::assets("/images/icon/logo-douggs.png", assets::ABSOLUTE_URL) ?>" alt="DouggS">
                                </a>
                            </div>
                            <div class="login-form">
                                <form action="" id="register" method="post">
                                    <div class="form-group">
                                        <label for="name" class=" form-control-label"><?= router::label('name'); ?></label>
                                        <input type="text" id="name" name="name" placeholder="<?= router::label('name'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="email" class=" form-control-label"><?= router::label('email'); ?></label>
                                        <input type="email" id="email" name="email" placeholder="<?= router::label('email'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="document" class=" form-control-label"><?= router::label('document'); ?></label>
                                        <input type="text" id="document" name="document" placeholder="<?= router::label('document'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="birthday" class=" form-control-label"><?= router::label('birthday'); ?></label>
                                        <input type="text" id="birthday" name="birthday" placeholder="<?= router::label('birthday'); ?>" class="form-control" data-provide="datepicker"  data-date-format="yyyy-mm-dd">
                                    </div>
                                    <div class="form-group">
                                        <label for="genre" class=" form-control-label"><?= router::label('genre'); ?></label>
                                        <select name="genre" id="genre" class="form-control">
                                            <option selected value="male">Masculino</option>
                                            <option value="female">Feminino</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="school" class=" form-control-label"><?= router::label('school'); ?></label>
                                        <select name="school" id="school" class="form-control">
                                            <option value="primário incompleto">Primário Incompleto</option>
                                            <option value="primário completo">Primário Completo</option>
                                            <option value="fundamental incompleto">Fundamental Incompleto</option>
                                            <option slectted value="fundamental completo">Fundamenta Completo</option>
                                            <option value="superior incompleto">Superior Incompleto</option>
                                            <option value="superior completo">Superior Completo</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="office" class=" form-control-label"><?= router::label('office'); ?></label>
                                        <input type="text" id="office" name="office" placeholder="<?= router::label('office'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="password" class=" form-control-label"><?= router::label('password'); ?></label>
                                        <input type="password" id="password" name="password" placeholder="<?= router::label('password'); ?>" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="confirm_password" class=" form-control-label"><?= router::label('confirm_password'); ?></label>
                                        <input type="password" id="confirm_password" name="confirm_password" placeholder="<?= router::label('confirm_password'); ?>" class="form-control">
                                    </div>
                                    <div class="login-checkbox">
                                        <label>
                                            <input type="checkbox" id="aggree" name="aggree"><?= router::label('policy_terms'); ?>
                                        </label>
                                    </div>
                                    <input type="hidden" name="pub_key" value="cmVnaXN0ZXJfZm9ybQ==">
                                    <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit"><?= router::label('register'); ?></button>
                                    <!-- <div class="social-login-content">
                                        <div class="social-button">
                                            <button class="au-btn au-btn--block au-btn--blue m-b-20"><?= router::label('register_with_facebook'); ?></button>
                                            <button class="au-btn au-btn--block au-btn--blue2"><?= router::label('register_with_twitter'); ?></button>
                                        </div>
                                    </div> -->
                                </form>
                                <div class="register-link">
                                    <p>
                                    <?= router::label('already_have_account'); ?>
                                        <a href="#"><?= router::label('sign_in'); ?></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                $('#register').submit(function() {
                    if($('#password').val() != $('#confirm_password').val()){
                        alert('<?= router::label('msg_confirm_password'); ?>')
                        return false;
                    }

                    if(!$('#aggree').is(':checked')){
                        alert('<?= router::label('msg_aggree'); ?>')
                        return false;
                    }

                    return true;
                });
            </script>
