<?php

namespace douggonsouza\benchmarck;

//definições dos templates

define('defaultLayout', __DIR__ . '/layouts/default.phtml');
define('dashboard', __DIR__ . '/layouts/dashboard.phtml');
define('dashboardCssBlock', __DIR__ . '/blocks/dashboardCssBlock.phtml');
define('dashboardHeaderMobileBlock', BASE_DIR . '/src/views/dashboardHeaderMobileBlock.phtml');
define('dashboardMenuSidebarBlock', BASE_DIR . '/src/views/dashboardMenuSidebarBlock.phtml');
define('dashboardPageContainerBlock', __DIR__ . '/blocks/dashboardPageContainerBlock.phtml');
define('dashboardPageContainerHeaderDesktopBlock', __DIR__ . '/blocks/dashboardPageContainerHeaderDesktopBlock.phtml');
define('dashboardPageContainerMainContentBlock', __DIR__ . '/blocks/dashboardPageContainerMainContentBlock.phtml');
define('dashboardPageContainerMainContentPageBlock', __DIR__ . '/blocks/dashboardPageContainerMainContentPageBlock.phtml');
define('dashboardPageContainerBreakcrumbBlock', __DIR__ . '/blocks/dashboardPageContainerBreakcrumbBlock.phtml');
define('dashboardPageContainerMainContentNewPageBlock', __DIR__ . '/blocks/dashboardPageContainerMainContentNewPageBlock.phtml');
define('dashboardPageContainerMainContentStepOneBlock', __DIR__ . '/blocks/dashboardPageContainerMainContentStepOneBlock.phtml');
define('dashboardPageContainerMainContentAccessesPagesBlock', __DIR__ . '/blocks/dashboardPageContainerMainContentAccessesPagesBlock.phtml');
define('dashboardPageContainerMainContentAlertsBlock', __DIR__ . '/blocks/dashboardPageContainerMainContentAlertsBlock.phtml');
define('dashboardJsBlock', __DIR__ . '/blocks/dashboardJsBlock.phtml');
define('dashboard1', __DIR__ . '/layouts/dashboard1.phtml');
define('dashboard1CssBlock', __DIR__ . '/blocks/dashboard1CssBlock.phtml');
define('dashboard1MenuSidebarBlock', BASE_DIR . '/src/views/dashboard1MenuSidebarBlock.phtml');
define('dashboard1PageContainerBlock', __DIR__ . '/blocks/dashboard1PageContainerBlock.phtml');
define('dashboard1HeaderMobileBlock', BASE_DIR . '/src/views/dashboard1HeaderMobileBlock.phtml');
define('dashboard1PageContainerAlertsBlock', __DIR__ . '/blocks/dashboard1PageContainerAlertsBlock.phtml');
define('dashboard1PageContainerHeaderWrapBlock', __DIR__ . '/blocks/dashboard1PageContainerHeaderWrapBlock.phtml');
define('dashboard1PageContainerMenuSidebarBlock', BASE_DIR . '/src/views/dashboard1PageContainerMenuSidebarBlock.phtml');
define('dashboard1PageContainerHeaderDesktopBlock', __DIR__ . '/blocks/dashboard1PageContainerHeaderDesktopBlock.phtml');
define('dashboard1PageContainerBreakcrumbBlock', __DIR__ . '/blocks/dashboard1PageContainerBreakcrumbBlock.phtml');
define('dashboard1PageContainerPageBlock', __DIR__ . '/blocks/dashboard1PageContainerPageBlock.phtml');
define('dashboard1PageContainerPerfilBlock', __DIR__ . '/blocks/dashboard1PageContainerPerfilBlock.phtml');
define('dashboard1PageContainerStatisticBlock', __DIR__ . '/blocks/dashboard1PageContainerStatisticBlock.phtml');
define('dashboard1PageContainerRecentReport2Block', __DIR__ . '/blocks/dashboard1PageContainerRecentReport2Block.phtml');
define('dashboard1PageContainerTaskProgressBlock', __DIR__ . '/blocks/dashboard1PageContainerTaskProgressBlock.phtml');
define('dashboard1PageContainerUserDataBlock', __DIR__ . '/blocks/dashboard1PageContainerUserDataBlock.phtml');
define('dashboard1PageContainerMapDataBlock', __DIR__ . '/blocks/dashboard1PageContainerMapDataBlock.phtml');
define('dashboard1PageContainerCopyrightBlock', __DIR__ . '/blocks/dashboard1PageContainerCopyrightBlock.phtml');
define('dashboard1JsBlock', __DIR__ . '/blocks/dashboard1JsBlock.phtml');
define('dashboard2', __DIR__ . '/layouts/dashboard2.phtml');
define('dashboard2CssBlock', __DIR__ . '/blocks/dashboard2CssBlock.phtml');
define('dashboard2HeaderDesktopBlock', BASE_DIR . '/src/views/dashboard2HeaderDesktopBlock.phtml');
define('dashboard2HeaderMobileBlock', BASE_DIR . '/src/views/dashboard2HeaderMobileBlock.phtml');
define('dashboard2HeaderMobileToolBlock', __DIR__ . '/blocks/dashboard2HeaderMobileToolBlock.phtml');
define('dashboard2PageContentAlertsBlock', __DIR__ . '/blocks/dashboard2PageContentAlertsBlock.phtml');
define('dashboard2PageContentBlock', __DIR__ . '/blocks/dashboard2PageContentBlock.phtml');
define('dashboard2PageContentBreadcrumbBlock', __DIR__ . '/blocks/dashboard2PageContentBreadcrumbBlock.phtml');
define('dashboard2PageContentWelcomeBlock', __DIR__ . '/blocks/dashboard2PageContentWelcomeBlock.phtml');
define('dashboard2PageContentPageBlock', __DIR__ . '/blocks/dashboard2PageContentPageBlock.phtml');
define('dashboard2PageContentStatisticBlock', __DIR__ . '/blocks/dashboard2PageContentStatisticBlock.phtml');
define('dashboard2PageContentStatisticChartBlock', __DIR__ . '/blocks/dashboard2PageContentStatisticChartBlock.phtml');
define('dashboard2PageContentDataTableBlock', __DIR__ . '/blocks/dashboard2PageContentDataTableBlock.phtml');
define('dashboard2PageContentCopyrightBlock', __DIR__ . '/blocks/dashboard2PageContentCopyrightBlock.phtml');
define('dashboard2JsBlock', __DIR__ . '/blocks/dashboard2JsBlock.phtml');
define('dashboard3', __DIR__ . '/layouts/dashboard3.phtml');
define('login', __DIR__ . '/layouts/login.phtml');
define('loginCssBlock', __DIR__ . '/blocks/loginCssBlock.phtml');
define('loginJsBlock', __DIR__ . '/blocks/loginJsBlock.phtml');
define('loginAlertsBlock', __DIR__ . '/blocks/loginAlertsBlock.phtml');
define('loginPageContentBlock', __DIR__ . '/blocks/loginPageContentBlock.phtml');
define('register', __DIR__ . '/layouts/register.phtml');
define('registerCssBlock', __DIR__ . '/blocks/registerCssBlock.phtml');
define('registerJsBlock', __DIR__ . '/blocks/registerJsBlock.phtml');
define('registerAlertsBlock', __DIR__ . '/blocks/registerAlertsBlock.phtml');
define('registerPageContentBlock', __DIR__ . '/blocks/registerPageContentBlock.phtml');
define('forgetpass', __DIR__ . '/layouts/forget-pass.phtml');
define('forgetpassCssBlock', __DIR__ . '/blocks/forgetpassCssBlock.phtml');
define('forgetpassJsBlock', __DIR__ . '/blocks/forgetpassJsBlock.phtml');
define('forgetpassPageContentAlertsBlock', __DIR__ . '/blocks/forgetpassPageContentAlertsBlock.phtml');
define('forgetpassPageContentBlock', __DIR__ . '/blocks/forgetpassPageContentBlock.phtml');
?>