<!DOCTYPE html>
<html lang="pt-br">
<?php
    use douggonsouza\routes\router;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="<?= router::label('author'); ?>">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <!-- CSS BLOCO -->
    
    <?php
        router::block('dashboardCssBlock', $params);
    ?>

    <!-- END CSS BLOCO -->

</head>

<body class="animsition">

    <!-- JS BLOCO -->

    <?php
        router::block('dashboardJsBlock', $params);
    ?>

    <!-- END JS BLOCO -->
    
    <div class="page-wrapper">

        <!-- HEADER MOBILE-->

        <?php
            router::block('dashboardHeaderMobileBlock', $params);
        ?>

        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->

        <?php
            router::block('dashboardMenuSidebarBlock', $params);
        ?>

        <!-- END MENU SIDEBAR-->

        <div class="page-container">

            <!-- BLOCO -->

            <!-- PAGE CONTAINER-->
            <!-- dashboardPageContainerBlock -->

            <?php
                router::block('dashboardPageContainerBlock', $params);
            ?>

            <!-- END PAGE CONTAINER-->
        </div>

    </div>
</body>

</html>
<!-- end document-->
