<!DOCTYPE html>
<html lang="pt-br">
<?php 
    use douggonsouza\routes\router;
    use douggonsouza\alerts\alerts;
    use douggonsouza\benchmarck\assets\assets;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard 2</title>

    <!-- BLOCO -->
    <!-- dashboard2CssBlock -->

        <?php
            router::identify('dashboard2CssBlock', $params);
        ?>

    <!-- BLOCO -->

</head>

<body class="animsition">

    <!-- BLOCO -->
    <!-- dashboard2JsBlock -->

    <?php
        router::identify('dashboard2JsBlock', $params);
    ?>

    <!-- BLOCO -->
    
    <div class="page-wrapper">

        <!-- BLOCO -->
        <!-- dashboard2HeaderDesktopBlock -->
        <!-- HEADER DESKTOP-->

            <?php
                router::identify('dashboard2HeaderDesktopBlock', $params);
            ?>

        <!-- END HEADER DESKTOP-->
        <!-- BLOCO -->

        <!-- BLOCO -->
        <!-- dashboard2HeaderMobileBlock -->
        <!-- HEADER MOBILE-->

            <?php
                router::identify('dashboard2HeaderMobileBlock', $params);
            ?>

            <!-- BLOCO -->
            <!-- dashboard2HeaderMobileToolBlock-->
            <!-- HEADER TOOL-->

            <?php
                router::identify('dashboard2HeaderMobileToolBlock', $params);
            ?>

        <!-- END HEADER MOBILE -->
        <!-- BLOCO -->

            <div class="page-content--bgf7">

                <!-- BLOCO -->
                <!-- dashboard2AlertsBlock -->

                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card-body">
                                    <div class="sufee-alert alert with-close alert-primary alert-dismissible fade show">
                                        <span class="badge badge-pill badge-primary">Success</span>
                                        You successfully read this important alert.
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <?php
                                        if(alerts::exist()){
                                            alerts::get();
                                        }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- BLOCO -->

                <!-- BLOCO -->
                <!-- dashboard2PageContentBlock -->
                <!-- PAGE CONTENT-->

                <?php
                    router::identify('dashboard2PageContentBlock', $params);
                ?>

            </div>

        <!-- PAGE CONTENT-->
        <!-- BLOCO -->

    </div>
</body>

</html>
<!-- end document-->
