<!DOCTYPE html>
<html lang="pt-br">
<?php
    use douggonsouza\routes\router;
    use douggonsouza\alerts\alerts;
    use douggonsouza\benchmarck\assets\assets;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <!-- CSS BLOCO -->
    
    <?php
        router::identify('dashboardCssBlock', $params);
    ?>

    <!-- END CSS BLOCO -->

</head>

<body class="animsition">

    <!-- JS BLOCO -->

    <?php
        router::identify('dashboardJsBlock', $params);
    ?>

    <!-- END JS BLOCO -->
    
    <div class="page-wrapper">

        <!-- HEADER MOBILE-->

        <?php
            router::identify('dashboardHeaderMobileBlock', $params);
        ?>

        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->

        <?php
            router::identify('dashboardMenuSidebarBlock', $params);
        ?>

        <!-- END MENU SIDEBAR-->

        <div class="page-container">

            <!-- BLOCO -->

            <!-- PAGE CONTAINER-->

            <?php
                router::page($params);
            ?>

            <!-- END PAGE CONTAINER-->
        </div>

    </div>
</body>

</html>
<!-- end document-->
