<!DOCTYPE html>
<html lang="pt-br">
<?php
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard 2</title>

    <!-- BLOCO -->
    <!-- dashboard1CssBlock -->

    <?php
        // router::block('\\discovery\\controls\\login:loginFrame', $params);
        router::identify('dashboard1CssBlock', $params);
    ?>

    <!-- BLOCO -->

</head>

<body class="animsition">
    <div class="page-wrapper">

        <!-- BLOCO -->
        <!-- dashboard1MenuSidebar -->
        <!-- MENU SIDEBAR-->

        <?php
            router::identify('dashboard1MenuSidebarBlock', $params);
        ?>

        <!-- END MENU SIDEBAR-->
        <!-- BLOCO -->

            <div class="page-container2">

            <!-- BLOCO -->
            <!-- dashboard1PageContainer -->
            <!-- PAGE CONTAINER-->

            <?php
                router::identify('dashboard1PageContainerBlock', $params);
            ?>

            </div>

        <!-- END PAGE CONTAINER-->
        <!-- BLOCO -->

    </div>

    <!-- BLOCO -->
    <!-- dashboard1PageContainer -->

    <?php
        router::identify('dashboard1JsBlock', $params);
    ?>

    <!-- BLOCO -->

</body>

</html>
<!-- end document-->
