<!DOCTYPE html>
<html lang="pt-br">
<?php 
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="<?= router::label('author'); ?>">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard 2</title>

    <!-- BLOCO -->
    <!-- dashboard2CssBlock -->

        <?php
            router::block('dashboard2CssBlock', $params);
        ?>

    <!-- BLOCO -->

</head>

<body class="animsition">

    <!-- BLOCO -->
    <!-- dashboard2JsBlock -->

    <?php
        router::block('dashboard2JsBlock', $params);
    ?>

    <!-- BLOCO -->
    
    <div class="page-wrapper">

        <!-- BLOCO -->
        <!-- dashboard2HeaderDesktopBlock -->
        <!-- HEADER DESKTOP-->

            <?php
                router::block('dashboard2HeaderDesktopBlock', $params);
            ?>

        <!-- END HEADER DESKTOP-->
        <!-- BLOCO -->

        <!-- BLOCO -->
        <!-- dashboard2HeaderMobileBlock -->
        <!-- HEADER MOBILE-->

            <?php
                router::block('dashboard2HeaderMobileBlock', $params);
            ?>

            <!-- BLOCO -->
            <!-- dashboard2HeaderMobileToolBlock-->
            <!-- HEADER TOOL-->

            <?php
                router::block('dashboard2HeaderMobileToolBlock', $params);
            ?>

        <!-- END HEADER MOBILE -->
        <!-- BLOCO -->

            <div class="page-content--bgf7">

                <!-- BLOCO -->
                <!-- dashboard2PageContentBlock -->
                <!-- PAGE CONTENT-->

                <?php
                    router::content($params);
                ?>

            </div>

        <!-- PAGE CONTENT-->
        <!-- BLOCO -->

    </div>
</body>

</html>
<!-- end document-->
