<!DOCTYPE html>
<html lang="pt-br">
<?php 
    use douggonsouza\routes\router;
    use douggonsouza\alerts\alerts;
    use douggonsouza\benchmarck\assets\assets;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Forget Password</title>

    <!-- BLOCO -->
    <!-- forget-passCssBlock -->

        <?php
            router::identify('forgetpassCssBlock', $params);
        ?>

    <!-- BLOCO -->

</head>

<body class="animsition">

    <!-- BLOCO -->
    <!-- forget-passJsBlock -->

    <?php
            router::identify('forgetpassJsBlock', $params);
        ?>

    <!-- BLOCO -->
    
    <div class="page-wrapper">

        <!-- BLOCO -->
        <!-- forgetpassAlertsBlock -->

        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card-body">
                            <div class="sufee-alert alert with-close alert-primary alert-dismissible fade show">
                                <span class="badge badge-pill badge-primary">Success</span>
                                You successfully read this important alert.
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <?php
                                if(alerts::exist()){
                                    alerts::get();
                                }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- BLOCO -->

        <!-- BLOCO -->
        <!-- forget-passPageContentBlock -->

            <?php
                router::identify('forgetpassPageContentBlock', $params);
            ?>

        <!-- BLOCO -->

    </div>
</body>

</html>
<!-- end document-->