<!DOCTYPE html>
<html lang="pt-br">
<?php 
    use douggonsouza\routes\router;
    use douggonsouza\alerts\alerts;
    use douggonsouza\benchmarck\assets\assets;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Login</title>

    <!-- CSS BLOCO -->
    <!-- loginCssBlock -->

        <?php
            router::identify('loginCssBlock', $params);
        ?>

    <!-- BLOCO -->

</head>

<body class="animsition">

    <!-- BLOCO -->
    <!-- loginJsBlock -->

    <?php
            router::identify('loginJsBlock', $params);
        ?>

    <!-- BLOCO -->

    <div class="page-wrapper">

        <!-- BLOCO -->
        <!-- loginAlertsBlock -->

        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card-body">
                            <?php
                                if(alerts::exist()){
                                    alerts::get();
                                }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- BLOCO -->

        <!-- BLOCO -->
        <!-- loginPageContent -->

            <?php
                router::identify('loginPageContentBlock', $params);
            ?>

        <!-- BLOCO -->

    </div>
</body>

</html>
<!-- end document-->