<!DOCTYPE html>
<html lang="pt-br">
<?php 
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Login</title>

    <!-- CSS BLOCO -->
    <!-- loginCssBlock -->

        <?php
            router::identify('loginCssBlock', $params);
        ?>

    <!-- BLOCO -->

</head>

<body class="animsition">
    <div class="page-wrapper">

        <!-- BLOCO -->
        <!-- loginPageContent -->

            <?php
                router::identify('loginPageContentBlock', $params);
            ?>

        <!-- BLOCO -->

    </div>

    <!-- BLOCO -->
    <!-- loginJsBlock -->

        <?php
            router::identify('loginJsBlock', $params);
        ?>

    <!-- BLOCO -->

</body>

</html>
<!-- end document-->