<!DOCTYPE html>
<html lang="pt-br">
<?php 
    use douggonsouza\routes\router;
    use douggonsouza\benchmarck\assets\assets;
?>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="<?= router::label('author'); ?>">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Register</title>

    <!-- CSS BLOCO -->
    <!-- registerCssBlock -->

        <?php
            router::block('registerCssBlock', $params);
        ?>

    <!-- BLOCO -->

</head>

<body class="animsition">

    <!-- BLOCO -->
    <!-- registerJsBlock -->

    <?php
            router::block('registerJsBlock', $params);
        ?>

    <!-- BLOCO -->
    
    <div class="page-wrapper">

        <!-- BLOCO -->
        <!-- registerAlertsBlock -->

        <?php
            router::block('registerAlertsBlock', $params);
        ?>

        <!-- BLOCO -->

        <!-- BLOCO -->
        <!-- registerPageContentBlock -->

            <?php
                router::block('registerPageContentBlock', $params);
            ?>

        <!-- BLOCO -->

    </div>

</body>

</html>
<!-- end document-->